qnd111app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd111app/shop/urls.py
from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('cart_list/', views.cart_list, name='cart_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

qnd111app/shop/models.py
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.models import Page
from wagtail_localize.models import TranslatableMixin
from django.urls import reverse

class Category(TranslatableMixin, models.Model):
    name = models.CharField(max_length=200, db_index=True, null=True)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, null=True)
    salidas = models.DateTimeField(null=True)
    desde = models.CharField(max_length=200, null=True)
    description = models.TextField(blank=True, null=True)
    detail = models.FileField(upload_to='tours/%Y/%m/%d', null=True)
    terms = models.TextField(blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel('name'),
        FieldPanel('slug'),
        FieldPanel('image'),
        FieldPanel('salidas'),
        FieldPanel('desde'),
        FieldPanel('description'),
        FieldPanel('detail'),
        FieldPanel('terms'),
    ]

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        constraints = [
            models.UniqueConstraint(fields=['translation_key', 'locale'], name='unique_translation_key_locale_shop_category')
        ]

    def __str__(self):
        return self.name or str(self.id)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])





class Product(TranslatableMixin, models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True)
    available = models.BooleanField(default=True)
    item1 = models.CharField(max_length=200, null=True)
    item2 = models.CharField(max_length=200, null=True)
    item3 = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image_2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image_3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        constraints = [
            models.UniqueConstraint(fields=['translation_key', 'locale'], name='unique_translation_key_locale_shop_product')
        ]

qnd111app/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def cart_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/cart_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                id=id,
                                translations__language_code=language,
                                translations__slug=slug,
                                available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)

    cart_product_form = CartAddProductForm()

    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                  'category': category,
                  'cart_product_form': cart_product_form,
                  'recommended_products': recommended_products,
                  'products': products})

qnd111app/shop/templates/shop/product/cart_list.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load wagtailcore_tags wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}





{% block content %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% include 'shop/list_header.html' %}

<div id="wrapper">
  <!-- content -->	
  <div class="content">
    
      <!-- column-image  -->	
      <div class="column-image">
          <div class="bg"  data-bg="{% static 'img/1.jpg' %}"></div>
          <div class="overlay"></div>
          <div class="column-title">
            <img src="{% static '/img/logo_flor.png' %} " width=300px>
              <h2 style="font-size: 100px;"><i class="fal fa-shopping-cart"></i></h2>
              <p>{% trans "Make your reservations online and pay now, easily and securely." %}</p>
          </div>
      
          <div class="fixed-column-dec"></div>
      </div>
      <!-- column-image end  -->	
      <!-- column-wrapper -->	
      <div class="column-wrapper  single-content-section">
    
          <!-- fixed-bottom-content-->	
       
          <!-- fixed-bottom-content end -->	
          <!--section  -->	
   
          <section class="single-content-section">
              <div class="container small-container">
               
                  <!-- post -->
                  
                  <div class="post fl-wrap fw-post">
                    <div id="subheader">
                        <div class="cart">
                          {% with total_items=cart|length %}
                              {% if cart|length > 0 %}
                                <h2 style="font-size:30px;">{% trans "Your" %}  <i class="fal fa-shopping-cart"></i> {% trans "reservation shopping" %} {% trans "have to "%}:
                                <a href="{% url "cart:cart_detail" %}">
                                  {% blocktrans with total_items_plural=total_items|pluralize  total_price=cart.get_total_price %}
                                  <p> <li>{{ total_items }}  passengers tour reservation
                                   {{ total_items_plural }}:
                                    ${{ total_price }}</li></p>
                                  {% endblocktrans %}
                                
                                </a>
            
                              {% else %}
                               <h2>{% trans "Your" %}<i class="fal fa-shopping-cart"></i>  {% trans "is empty." %}</h2> 
                              {% endif %}
                            {% endwith %}
                        </h2>
                        </div>
                      </div>
                      
                      
                      <!-- blog media end -->
                   
                 

              </div>
          </section>
         
          <!--section end  -->	
          <!--footer -->			
          <footer class="min-footer fl-wrap content-animvisible">
              <div class="container small-container">
                  <div class="footer-inner fl-wrap">
                      <!-- policy-box-->
                      <div class="policy-box">
                        <span> Design by Edward Cooper /&#169; Powered by <img src="{% static 'img/logo_smartquailWW.png' %}" width="130px">   </span>
                      </div>
                      <!-- policy-box end-->
                    
                  </div>
              </div>
          </footer>
          <!--footer end  -->	
      </div>
      <!-- column-wrapper -->	
  </div>
  <!--content end-->	
  <!--share-wrapper-->
  <div class="share-wrapper">
      <div class="share-container fl-wrap  isShare"></div>
  </div>
  <!--share-wrapper end-->
</div>
{% endblock %}

qnd111app/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load wagtailcore_tags wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}

{% include 'shop/list_header.html' %}

<div id="wrapper">
    <!-- content -->	
    <div class="content">
        <!-- column-image  -->	
        <div class="column-image">
            <div class="bg"  data-bg="{% static "img/2.jpg" %}" ></div>       
            <div class="overlay"></div>
            
            <div class="column-title">
              <img src="{% static 'img/logo_flor.png' %}" width="350px">
              
                <h2>{{ product.category }}</h2>
                <div class="overlay"></div>
            </div>
        
            <div class="fixed-column-dec"></div>
        </div>

        <!-- column-image end  -->	
        <!-- column-wrapper -->	
        <div class="column-wrapper single-content-section">
          <!--fixed-bottom-content -->	
        
          <!--fixed-bottom-content end  -->	
          <!--section  -->	
           <section class="single-content-section">
              <div class="container small-container">
                  <!-- post -->
                  <div class="post fl-wrap fw-post single-post ">
                    {% for p in products %}
                    {% if product.slug == p.slug %}{% endif %}
                      <h2><span>{{ p.name }}</span></h2>
                    {% endfor %}
                    
                      <!-- blog media -->
                      <div class="blog-media fl-wrap">
                          <div class="single-slider-wrap">
                              <div class="single-slider fl-wrap">
                                  <div class="swiper-container">
                                      <div class="swiper-wrapper lightgallery">
                                          <div class="swiper-slide hov_zoom"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><a href="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="box-media-zoom   popup-image"><i class="fal fa-search"></i></a></div>
                                          <div class="swiper-slide hov_zoom"><img src="{% if product.image_2 %}{{ product.image_2.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><a href="{% if product.image %}{{ product.image_2.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="box-media-zoom   popup-image"><i class="fal fa-search"></i></a></div>
                                          <div class="swiper-slide hov_zoom"><img src="{% if product.image_3 %}{{ product.image_3.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><a href="{% if product.image %}{{ product.image_3.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="box-media-zoom   popup-image"><i class="fal fa-search"></i></a></div>
                                         
                                      </div>
                                  </div>
                              </div>
                              <div class="ss-slider-pagination_wrap">
                                  <div class="ss-slider-pagination"></div>
                              </div>
                              <div class="ss-slider-cont ss-slider-cont-prev color-bg"><i class="fal fa-long-arrow-left"></i></div>
                              <div class="ss-slider-cont ss-slider-cont-next color-bg"><i class="fal fa-long-arrow-right"></i></div>
                          </div>
                      </div>
                      <!-- blog media end -->
                      <div class="blog-text fl-wrap">
                          <div class="pr-tags fl-wrap">
                              <span>Details : </span>
                              <ul>
                                  <li><a href="#">{{ product.item1 }}</a></li>
                                  <li><a href="#">{{ product.item2 }}</a></li>
                                  <li><a href="#">{{ product.item3 }}</a></li>
                              </ul>
                          </div>
                          <p>{{ product.description|linebreaks }}
                          </p>
                        
                      </div>
                      <!-- post-author-->                                   
                      
                      <!--post-author end-->
                      <div id="comments" class="single-post-comm fl-wrap">
                          <!--title-->
                      
                        
                              <h2 id="reply-title">{% trans "Make you reservation now" %}
                              
                              </h2>
                             
                              <form class="custom-form" name="commentform"  action="{% url "cart:cart_add" product.id %}" method="post">
                                <fieldset>
                                    <label for="{{ form.quantity }}"><h2>{% trans "Number of persons on Tour" %} :</h2></label>  
                                {% csrf_token %}
                                      {% for hidden_field in cart_product_form.hidden_fields %}
                                        {{ hidden_field }}
                                      {% endfor %}
                                      
                                      {% if cart_product_form.non_field_errors %}
                                        <div class="alert alert-danger" role="alert">
                                        {% for error in cart_product_form.non_field_errors %}
                                          {{ error }}
                                        {% endfor %}
                                        </div>
                                      {% endif %}
                                      
                                      {% for field in cart_product_form.visible_fields %}
                                        <div class="custom-form">
                                        {{ field.label_tag }}
                                      
                                        {% if cart_product_form.is_bound %}
                                          {% if field.errors %}
                                          {% render_field field class="form-control is-invalid" %}
                                          {% for error in field.errors %}
                                            <div class="invalid-feedback">
                                            {{ error }}
                                            </div>
                                          {% endfor %}
                                          {% else %}
                                          {% render_field field class="form-control is-valid" %}
                                          {% endif %}
                                        {% else %}
                                          {% render_field field class="form-control" %}
                                        {% endif %}
                                      
                                        {% if field.help_text %}
                                          <small class="form-text text-muted">{{ field.help_text }}</small>
                                          
                                        {% endif %}
                                        </div>
                                      {% endfor %} 
                                <button class="btn float-btn" type="submit">{% trans "Add a cart" %}  <i class="fal fa-shopping-cart"></i> </button>
                              </fieldset>
                              </form>
                          </div>
                          <!--end respond-->
                      </div>
                      <!--comments end -->
                  </div>
                  <!-- post end-->

                  
              
            </section>
            <footer class="min-footer fl-wrap content-animvisible">
                <div class="container small-container">
                    <div class="footer-inner fl-wrap">
                        <!-- policy-box-->
                        <div class="policy-box">
                          <span> Design by Edward Cooper /&#169; Powered by <img src="{% static 'img/logo_smartquailWW.png' %}" width="130px">   </span>
                        </div>
                        <!-- policy-box end-->
                        <a href="#" class="to-top-btn to-top">Back to top <i class="fal fa-long-arrow-up"></i></a>
                    </div>
                </div>
            </footer>
            </div>
            
        
        <!-- column-wrapper -->	
    </div>
    
    <!--content end-->	
    <!--share-wrapper-->
    <div class="share-wrapper">
        <div class="share-container fl-wrap  isShare"></div>
    </div>
    <!--share-wrapper end-->
</div>
{% endblock %}

qnd111app/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load wagtailcore_tags wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}





{% block content %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% include 'shop/list_header.html' %}

<div id="wrapper">
  <!-- content -->	
  <div class="content">
    
      <!-- column-image  -->	
      <div class="column-image">
          <div class="bg"  data-bg="{% static 'img/1.jpg' %}"></div>
          <div class="overlay"></div>
          <div class="column-title">
            <img src="{% static '/img/logo_flor.png'%}" width="350px">
            
              <h2>{% trans "Expeditions" %}</h2>
              <p>{% trans "GET THE MOST OUT OF FLOREANA" %}</p>
              <div class="overlay"></div>
          </div>
      
          <div class="fixed-column-dec"></div>
      </div>
      <!-- column-image end  -->	
      <!-- column-wrapper -->	
      <div class="column-wrapper  single-content-section">
    
          <!-- fixed-bottom-content-->	
       
          <!-- fixed-bottom-content end -->	
          <!--section  -->	
   
          <section class="single-content-section">
              <div class="container small-container">
               
                  <!-- post -->
                  {% for c in categories %}
                      {% if category.slug == c.slug %}{% endif %}
                      {% for product in products %}
                  <div class="post fl-wrap fw-post">   
                            
                    <a href="{{ c.get_absolute_url }}"><h2><span>{{ c.name }}</span></h2></a>
                    <h2>
                      {{ c.desde }}  
                 </h2> 
                      <!-- blog media -->
                      <div class="blog-media fl-wrap">
                        <img src="{% if c.image %}{{ c.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="400px">
                      </div>
                      
                      <!-- blog media end -->
                      <div class="blog-text fl-wrap">
                          <div class="pr-tags fl-wrap"> 
                            <p>{{c.description}}</p>
                            <a href="{{ c.detail.url }}" >  <span>{% trans "Download here the description" %}    <i class="fal fa-solid fa-file"></i></span></a>
                          </div>
                         
                         
                          <a href="{{ product.get_absolute_url }}" class="btn float-btn flat-btn">Read more </a>
                          
                      </div>
                  </div>
                  {% endfor %}
                          {% endfor %}
                 

              </div>
              <a href="#" class="to-top-btn to-top">Back to top <i class="fal fa-long-arrow-up"></i></a>
          </section>
         
          <!--section end  -->	
          <!--footer -->			
          <footer class="min-footer fl-wrap content-animvisible">
              <div class="container small-container">
                  <div class="footer-inner fl-wrap">
                      <!-- policy-box-->
                      <div class="policy-box">
                        2022, <span> Design by Edward Cooper&#169; / Powered by <img src="{% static 'img/logo_smartquailWW.png' %}" width="130px">&#169; </span>
                      </div>
                      <!-- policy-box end-->
                     
                  </div>
              </div>
          </footer>
          <!--footer end  -->	
      </div>
      <!-- column-wrapper -->	
  </div>
  <!--content end-->	
  <!--share-wrapper-->
  <div class="share-wrapper">
      <div class="share-container fl-wrap  isShare"></div>
  </div>
  <!--share-wrapper end-->
</div>
{% endblock %}