qnd111app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd111app/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

qnd111app/orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path(_('Order_terms/'), views.order_term, name='order_term'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/phone', views.admin_order_phone, name='admin_order_phone'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

qnd111app/shop/urls.py
from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('cart_list/', views.cart_list, name='cart_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

qnd111app/cart/models.py
from django.db import models

# Create your models here.

qnd111app/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                label="",
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

class CouponApplyForm(forms.Form):
    code = forms.CharField()

qnd111app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm, CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form':coupon_apply_form})

qnd111app/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}



{% block content %}
{% include 'cart/detail_header.html' %}

<div id="wrapper">
  <!-- content -->	
  <div class="content">
      <!-- column-image  -->	
      <div class="column-image">
         
          <div class="overlay"></div>
          <div class="overlay"></div>
          
          <div class="bg"  data-bg="{% static 'img/4.jpg' %}"></div>
      <div class="overlay"></div> 
          <div class="column-title">
            
            <img src="{% static 'img/logo_flor.png' %}" width="350px">
            <div class="overlay"></div> 
              <h2>{% trans "Reservations" %}</h2>
          </div>

          

        
        
          <div class="fixed-column-dec"></div>
      </div>
      <!-- column-image end  -->	
      <!-- column-wrapper -->	
      <div class="column-wrapper  single-content-section">

          <!-- fixed-bottom-content-->	
        <div class="fixed-bottom-content">
                            <!-- pagination   -->
                            <div class="content-nav-fixed">
                                <ul>
                                    <li>
                                        <a href="{% url "shop:product_list" %}" class="ln"><i class="fal fa-long-arrow-left"></i><span> <strong>- {% trans "Continue shopping" %}</strong></span></a>
                                        <div class="content-nav_mediatooltip cnmd_leftside"><img  src="images/folio/1.jpg"   alt=""></div>
                                    </li>
                                    <li>
                                        <a href="{% url "orders:order_create" %}" class="rn">{% trans "CheckIn" %}<span > <strong><i class="fal fa-plane"></i> </strong></span> <i class="fal fa-long-arrow-right"></i></a>
                                        <div class="content-nav_mediatooltip cnmd_rightside"><img  src="images/folio/1.jpg"   alt=""></div>
                                    </li>
                                </ul>
                            </div>
        </div>
          <!-- fixed-bottom-content end -->	
          <!--section  -->	
        
          <section id="sec3">
            <div class="container small-container">
                <div class="section-title fl-wrap">
                  
                
                    <h3>{% trans "Make Reservations" %}</h3>
                    
                </div>
                <div class="column-wrapper_item fl-wrap">
                    <div class="column-wrapper_text fl-wrap">
                        <!-- serv-wrap--> 
                        <div class="serv-wrap fl-wrap">
                            <!-- serv-item --> 
                            {% for item in cart %}
                            {% with product=item.product %}
                           
                            <div class="serv-item">
                             
                              <h4>{{ product.name }}</h4>

                                <div class="serv-media">
                                  <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="300px">
                                  </a>
                                 
                                </div>

                                <div class="column-wrapper_item fl-wrap">
                                  
                                  <div class="column-wrapper_text fl-wrap">
                                      
                                      <div class="contact-details fl-wrap">
                                        
                                       
                                        
                                          <ul>
                                           
                                              <li><span>{% trans "Price per person "%} :</span>$ {{ item.price }}</li>
                                              <li><span>{% trans "Final Price" %} :</span>${{ item.total_price }}</li>
                                              <li><span># {% trans "persons" %} <i class="fal fa-user"></i> :</span> 
                                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                  {{ item.update_quantity_form.quantity }}
                                                  {{ item.update_quantity_form.update }}
                                                  <input type="submit" class="btn btn-primary btn-block" value="Update">
                                                  {% csrf_token %}
                                                </form> 
                                                <li>
                                                  <p>{% trans "Apply a Coupon" %}</p>
  <form action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply" class="btn btn-primary btn-block" >
    {% csrf_token %}
  </form>
                                                </li>
                                              <li>

                                                {% if cart.coupon %}
        <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
      </tr>
      <tr>
        <td>
          "{{ cart.coupon.code }}" coupon
          ({{ cart.coupon.discount }}% off )
        </td>
        <td colspan="4">
          <td class="num neg">
            - $ {{cart.get_discount|floatformat:"2" }}
          </td>
        </td>
      </tr>
      {% endif %}
                                              </li>
                                              
                                            
                                           
                                          
                                                <a href="{% url "cart:cart_remove" product.id %}" type="submit" value="Apply" class="btn btn-primary btn-block" > {% trans "Cancel" %}</a>
                                             
                                                
                                          </ul>
                                      </div>
                                
                                  </div>
                                
                              </div>

                              
                               
                            </div>
                            {% endwith %}
                              {% endfor %}
                           
                            <!-- serv-item end --> 
                            <!-- serv-item --> 
                            
                            <!-- serv-item end -->                                                  
                        </div>
                        <!-- serv-wrap end --> 
                        <p>{{product.description}}</p>
                    </div>
                </div>
            </div>

            
        </section>
       
          <!--section end  -->	
          <!--footer -->			
          <footer class="min-footer fl-wrap content-animvisible">
              <div class="container small-container">
                  <div class="footer-inner fl-wrap">
                      <!-- policy-box-->
                      <div class="policy-box">
                        <span>&#169; Powered by SmartQuail, Inc / Design by Edward Cooper  </span>
                      </div>
                      <!-- policy-box end-->
                      <a href="#" class="to-top-btn to-top">Back to top <i class="fal fa-long-arrow-up"></i></a>
                  </div>
              </div>
          </footer>
          <!--footer end  -->	
      </div>
      <!-- column-wrapper -->	
  </div>
  <!--content end-->	
  <!--share-wrapper-->
  <div class="share-wrapper">
      <div class="share-container fl-wrap  isShare"></div>
  </div>
  <!--share-wrapper end-->
</div>

{% endblock %}

qnd111app/cart/templates/cart/detail_header.html
{% load i18n %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load widget_tweaks %}
{% load static  %}




<head>
    <!--=============== basic  ===============-->
    <meta charset="UTF-8">
    <title>CENTRO COMUNINARIO-ISLA FLOREANA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="robots" content="index, follow"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <!--=============== css  ===============-->	
    <link type="text/css" rel="stylesheet" href="{% static 'css/reset_2.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style_3.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/payment.scss' %}">
    <!--=============== favicons ===============-->
    <link rel="shortcut icon" href="{% static '/img/favicon.ico' %}">
</head>


<header class="main-header">
    <!-- logo   -->
    
    <a href="{% slugurl 'home' %}" class="logo-holder"><img src="{% static 'img/logo_floreana.png' %}" alt="" ></a>  

    <!-- logo end  -->		
    <!-- search -->				
    
    <!-- search end  -->
  
    
   
    <div class="share-btn showshare"><i class="fal fa-share"></i><span>Share</span></div>
    <div class="share-btn"><a href="{% url 'shop:cart_list' %}"><i class="fal fa-shopping-cart"></i></a><span>Cart</span></div>
    <!-- mobile nav -->
    <div class="nav-button-wrap">
        <div class="nav-button"><span></span><span></span><span></span></div>
    </div>
    <!-- mobile nav end-->                
    <!--  navigation -->
    <div class="nav-holder main-menu">
        <nav>
            <ul>
                <li>
                    <a href="{% slugurl 'story' %}" class="act-link">{% trans "The Island" %} </a>
                </li>
                <li>
                    <a href="{% slugurl 'charms' %}">{% trans "Charms"%}</a>
                </li>
                <li>
                    <a href="{% slugurl 'worlds' %}">{% trans "Worlds" %}</a>
                    <ul>
                        <li><a href="index.html">{% trans "Natural Environ" %}</a></li>
                        <li><a href="index2.html">{% trans "Geological Environ" %}</a></li>
                        <li><a href="index3.html">{% trans "Marine Environ" %}</a></li>
                        <li><a href="index4.html">{% trans "Community Environ" %}</a></li>
                     
                    </ul>
                </li>
                <li>
                    <a href="{% slugurl 'hosts' %}">{% trans "Hosts" %}</a>
                </li>
                <li>
                    <a href="{% url 'shop:product_list' %}">{% trans "Expeditions" %}</a>
                </li>
                <li>
                    <a href="{% slugurl 'contacts' %}">{% trans "Contacts" %}</a>
                </li>
                <li>
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    <a href="#" class="act-link">{% trans "Languages" %} </a>
                    <ul class="languages">
                        {% for language in languages %}
                          <li>
                            <a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                              {{ language.name_local }}
                            </a>
                          </li>
                        {% endfor %}
                      </ul>
                   
                
                    <!--second level end-->
                </li>
            </ul>
        </nav>
    </div>
    <!-- navigation  end -->               
</header>