qnd111app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd111app/orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path(_('Order_terms/'), views.order_term, name='order_term'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/phone', views.admin_order_phone, name='admin_order_phone'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

qnd111app/orders/models.py
from django.db import models
from shop.models import Product
from decimal import Decimal
from django.contrib import admin
from phone_field import PhoneField
from django.core.validators import MinValueValidator, \
                                   MaxValueValidator
from coupons.models import Coupon
from django.utils.translation import gettext_lazy as _


class Order(models.Model):
    first_name = models.CharField(_('First name'), max_length=50)
    last_name = models.CharField(_('Last name'), max_length=50)
    email = models.EmailField(_('E-mail'))
    phone = models.CharField(blank=True, help_text=_('Contact phone number'),max_length=16)
    #address = models.CharField(_('address'), max_length=250)
    #postal_code = models.CharField(_('postal code'), max_length=20)
    #city = models.CharField(_('city'), max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL)
    arrival_date_time = models.DateTimeField(_('Date & time for Arrival to CC-floreana'),null=True)
    departure_date_time = models.DateTimeField(_('Date & time for Departure to CC-floreana'),null=True)
    #start_arrival_time = models.DateTimeField(_('Time for Arrival to CC-floreana'),null=True)
    #end_departure_time = models.DateTimeField(_('Time for Arrival to CC-floreana'),null=True)
    #departure = models.DateTimeField(_('Date for departure from CC-floreana'),null=True)
    agree_term = models.BooleanField(_('I accept the terms and conditions of this services.'),default=False,null=False,blank=False)
    total =  models.DecimalField(max_digits=1000, decimal_places=2,null=True,blank=True)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Reserva Online'
        verbose_name_plural = 'Reservas Online'

    def __str__(self):
        return 'Reserve to {}'.format(self.first_name +' '+ self.last_name)

    @property
    @admin.display(
        ordering='last_name',
        description='Full name',
    )
    def full_name(self):
        return self.first_name + ' ' + self.last_name



    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        total_price = total_cost - total_cost * (self.discount / Decimal('100'))
        return  total_price

    def save(self):
        self.total = self.get_total_cost()
        super (Order, self).save()

 


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

qnd111app/orders/forms.py
from django import forms
from .models import Order
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from .widget import DatePickerInput, TimePickerInput, DateTimePickerInput
from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput, MonthPickerInput, YearPickerInput


class MyDatePickerInput(DatePickerInput):
    template_name = 'orders/order/date-picker.html'


class OrderCreateForm(forms.ModelForm):
    agree_term = forms.BooleanField(required=True, help_text="I accept the terms and conditions of this services.")
    
    # Phone number field with default region (for CA in this case, but you can change it)
    phone = PhoneNumberField(
        region="CA",  # 'CA' for Canada, you can change it based on the default country you prefer
        widget=PhoneNumberPrefixWidget(
            widgets={
                'phone': forms.TextInput(attrs={'class': 'phone-input'}),
                'prefix': forms.Select(attrs={'class': 'prefix-select'})
            }
        ),
        help_text="Choice your local country extension number"
    )

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'arrival_date_time', 'departure_date_time', 'agree_term']
        
        widgets = {
            'arrival_date_time': DateTimePickerInput(format='%m/%d/%Y %H:%M'),
            'departure_date_time': DateTimePickerInput(format='%m/%d/%Y %H:%M'),
        }

qnd111app/orders/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import Order
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from shop.models import Category, Product


def order_create(request):
    cart = Cart(request)
    fields = ['arrival_date_time', 'firts_name']
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        form.fields['arrival_date_time'].widget = DateTimePickerInput()
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # launch asynchronous task
            order_created.delay(order.id)
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

def order_term(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'orders/order/term.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html,  base_url=request.build_absolute_uri() ).write_pdf(response,stylesheets=[weasyprint.CSS('staticfiles/css/pdf.css')], presentational_hints=True)
    return response

@staff_member_required
def admin_order_phone(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    response['Content-Disposition'] = '{}'.format(order.phone)
    return response

qnd111app/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}




{% block title %}
  {% trans "Checkout" %}
{% endblock %}

{% block content %}
{% include 'cart/detail_header.html' %}

<div id="wrapper">
  <!-- content -->	
  <div class="content">
      <!-- column-image  -->	

     
        
  <div class="column-image ">
         
          <div class="overlay"></div>
          <div class="bg"  data-bg="{% static 'img/6.jpg' %}"></div>
          
          <div class="column-title">
            <img src="{% static '/img/logo_flor.png' %} " width=350px>
            <h2>{% trans "Your list tours for Floreana Island:"  %}</h2>
            <div class="overlay"></div>
           
             
          
           
            <div class="section-title fl-wrap">
             

              
                
                  <div id="contact-form" class="fl-wrap">
                    <div class="container small-container">
      
                      
                {% for item in cart %}
                <ul>
                  <li><span>{% trans "Tour" %} :</span>{{ item.product.name }} </li>
                    <li><span># <i class="fal fa-user"></i>:</span>{{ item.quantity }}</li>
                    <li><span>Sub total :</span>${{ item.price|floatformat:"2" }}</li>
                    <li><span>Total :</span>${{ item.total_price|floatformat:"2" }}</li>
                    <li><span>Discount :</span>
                      {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                        {{ code }} ({{ discount }}% off)
                      {% endblocktrans %}
                      <span>- ${{ cart.get_discount|floatformat:"2" }}</span>
                    </li>
                    <p>{% trans "Total" %}: ${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
                </ul>
                {% endfor %}
              </div> 
            </div>  
          </div>
        </div> 
        
         
         
      </div>
     
      <!-- column-image end  -->	
      <!-- column-wrapper -->	
      <div class="column-wrapper ">

      </section>
          <section id="sec1">
              <div class="container small-container">
                <div class="section-title fl-wrap">
                  <h3>{% trans "Check In Now!" %}</h3>
                  <h3>{% trans "To Centro Comunitario Isla Floreana" %} <i class="fal fa-plane"></i></h3>
                  <p>{%  trans "Fill out the form below and you will receive an email confirmation of your Check In Track." %}</p>
                  </div>
                 
                  <div class="column-wrapper_item fl-wrap">
                      <div class="column-wrapper_text fl-wrap">
                          <div id="contact-form" class="fl-wrap">
                              <div id="message"></div>
                           
                              <form  class="custom-form" action="." method="post" >
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% if field.is_hidden %}
   {# Don't render label #}
{% endif %}
                                {% if  label.is_hidden %}
                                {{form.last_name}} {{sudaca}}
                                {% endif %}
                                {% for field in form.hidden_fields %}
                                {{ field }}
                               {% endfor %}
                               {% for field in  bootstrap_form.visible_fields %}
                                {{ field }}
                          
                                {% endfor %}
                               
                                 
  {% buttons %}
  
  <p><input type="submit" class="btn float-btn flat-btn color-bg" value="{% trans "Place order" %}"></p>
  <a href="{% url "orders:order_term"  %}" style="text-decoration: underline;"> {% trans "terms & conditions for reserve this service" %}</a>
  {% endbuttons %}
                                 
                                   
                                   
                                
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
          </section>


          <!--section end  -->	
          <!--footer -->			
          <footer class="min-footer fl-wrap content-animvisible">
              <div class="container small-container">
                  <div class="footer-inner fl-wrap">
                      <!-- policy-box-->
                      <div class="policy-box">
                          <span>&#169; 
                             Powered by SmartQuail, Inc / Design by Edward Cooper </span>
                      </div>
                      <!-- policy-box end-->
                      <a href="#" class="to-top-btn to-top">Back to top <i class="fal fa-long-arrow-up"></i></a>
                  </div>
              </div>
          </footer>
          <!--footer end  -->	
      </div>
      <!-- column-wrapper -->	
  </div>
  <!--content end-->	
  <!--share-wrapper-->
  <div class="share-wrapper">
      <div class="share-container fl-wrap  isShare"></div>
  </div>
  <!--share-wrapper end-->
</div>
{% endblock %}

qnd111app/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Thank you" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Thank you" %}</h1>
    <p>Your order has been successfully completed. </strong>.</p>

{% endblock %}

qnd111app/orders/templates/orders/order/date-picker.html
<h5>This is a customized date-picker</h5>
<div class="input-group date my-custom-class">
    {% include "bootstrap_datepicker_plus/input.html" %}
    <div class="input-group-addon input-group-append">
        <div class="input-group-text"><i class="glyphicon glyphicon-calendar"></i></div>
    </div>
</div>

qnd111app/orders/templates/orders/order/pdf.html
<html> 
<body> 
  <h1>My Shop</h1> 
  <p> 
    Invoice no. {{ order.id }}</br> 
    <span class="secondary"> 
      {{ order.created|date:"M d, Y" }} 
    </span> 
  </p> 
 
  <h3>Bill to</h3> 
  <p> 
    {{ order.first_name }} {{ order.last_name }}<br> 
    {{ order.email }}<br> 
    {{ order.address }}<br> 
    {{ order.postal_code }}, {{ order.city }} 
  </p> 
 
  <h3>Items bought</h3> 
  <table> 
    <thead> 
      <tr> 
        <th>Product</th> 
        <th>Price</th> 
        <th>Quantity</th> 
        <th>Cost</th> 
      </tr> 
    </thead> 
    <tbody> 
      {% for item in order.items.all %} 
        <tr class="row{% cycle "1" "2" %}"> 
          <td>{{ item.product.name }}</td> 
          <td class="num">${{ item.price }}</td> 
          <td class="num">{{ item.quantity }}</td> 
          <td class="num">${{ item.get_cost }}</td> 
        </tr> 
      {% endfor %} 
      <tr class="total"> 
        <td colspan="3">Total</td> 
        <td class="num">${{ order.get_total_cost }}</td> 
      </tr> 
    </tbody> 
  </table> 
     
  <span class="{% if order.paid %}paid{% else %}pending{% endif %}"> 
    {% if order.paid %}Paid{% else %}Pending payment{% endif %} 
  </span> 
</body> 
</html> 

qnd111app/orders/templates/orders/order/term.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}




{% block title %}
  {% trans "Checkout" %}
{% endblock %}

{% block content %}
{% include 'cart/detail_header.html' %}

<div id="wrapper">
  <!-- content -->	
  <div class="content">
      <!-- column-image  -->	

     
        
  <div class="column-image ">
         
          <div class="overlay"></div>
          
          <div class="column-title">
            <h2>{% trans "Your list tours for Floreana Island:"  %}</h2>
           
             
          
           
            <div class="section-title fl-wrap">
             

              
                
                  <div id="contact-form" class="fl-wrap">
                    <div class="container small-container">
      
                      
                {% for item in cart %}
                <ul>
                  <li><span>{% trans "Tour" %} :</span>{{ item.product.name }} </li>
                    <li><span># <i class="fal fa-user"></i>:</span>{{ item.quantity }}</li>
                    <li><span>Sub total :</span>${{ item.price|floatformat:"2" }}</li>
                    <li><span>Total :</span>${{ item.total_price|floatformat:"2" }}</li>
                    <li><span>Discount :</span>
                      {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                        {{ code }} ({{ discount }}% off)
                      {% endblocktrans %}
                      <span>- ${{ cart.get_discount|floatformat:"2" }}</span>
                    </li>
                    <p>{% trans "Total" %}: ${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
                </ul>
                {% endfor %}
              </div> 
            </div>  
          </div>
        </div> 
        
         
         
      </div>
     
      <!-- column-image end  -->	
      <!-- column-wrapper -->	
      <div class="column-wrapper ">
        <img src="{% static '/img/logo_flor.png' %} " width=300px>
<!--scroll-nav-wrap -->	
      </section>
							
          <section id="sec3">
              <div class="container small-container">
                <div class="section-title fl-wrap">
                    
                   <h3>{%  trans "TERMS & CONDITIONS OF ISLA FLOREANA GALAPAGOS RESERVATION SERVICE." %} </h3> 
                   
                 
        
                  </div>
                  {% for c in categories %}
                  {% if category.slug == c.slug %}{% endif %}
                  <div class="column-wrapper_item fl-wrap">
                      <div class="column-wrapper_text fl-wrap">
                          <div id="contact-form" class="fl-wrap">
                              <div id="message"></div>
                            
                            <p>{{c.name}}</p>   
                            
                              
                              {{ c.terms }}
                             
                          </div>
                      </div>
                  </div>
                 
                  {% endfor %}
                 
                  
              </div>

             
          </section>


          <!--section end  -->	
          <!--footer -->			
          <footer class="min-footer fl-wrap content-animvisible">
              <div class="container small-container">
                  <div class="footer-inner fl-wrap">
                      <!-- policy-box-->
                      <div class="policy-box">
                          <span>&#169; 
                             Powered by SmartQuail, Inc / Design by Edward Cooper </span>
                      </div>
                      <!-- policy-box end-->
                      <a href="{% url "cart:cart_detail" %}" class="to-top-btn">Back to Cart <i class="fal fa-shopping-cart"></i></a>
                  </div>
              </div>
          </footer>
          <!--footer end  -->	
      </div>
      <!-- column-wrapper -->	
  </div>
  <!--content end-->	
  <!--share-wrapper-->
  <div class="share-wrapper">
      <div class="share-container fl-wrap  isShare"></div>
  </div>
  <!--share-wrapper end-->
</div>
{% endblock %}

qnd111app/orders/templates/orders/order/time-picker.html
<h5>This is a customized time-picker</h5>
<div class="input-group date my-custom-class">
    {% include "bootstrap_datepicker_plus/input.html" %}
    <div class="input-group-addon input-group-append">
        <div class="input-group-text"><i class="glyphicon glyphicon-time"></i></div>
    </div>
</div>